apiVersion: v1
kind: Service
metadata:
  name: k8s-web-hello-service
spec:
  selector:
    app: k8s-web-hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer
