apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-hello-deployment
  labels:
    app: k8s-web-hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-web-hello-app
  template:
    metadata:
      labels:
        app: k8s-web-hello-app
    spec:
      containers:
        - name: k8s-web-hello-container
          image: eswarkondababu/k8s-web-hello
          ports:
            - containerPort: 3000
